Do not allow to run as user root, as it tshark does not work correctly when run as user root. See bug #13: https://sourceforge.net/p/callflow/bugs/13/

diff --git a/callflow b/callflow
--- a/callflow
+++ b/callflow
@@ -281,6 +281,11 @@ while true; do
   shift
 done
 
+[[ $(id -u) == 0 ]] && {
+  echo "$PRGNAME: error: do not run as user 'root'"
+  exit 1
+}
+
 inputfile="$1"
 if [[ ! -f "$inputfile" ]]; then
   echo "$PRGNAME: error: Input file ($inputfile) does not exists!"
