Callflow update. Easier to use. README update according to callflow changes.

diff --git a/callflow b/callflow
--- a/callflow
+++ b/callflow
@@ -15,7 +15,10 @@
 SETUPDIR="/usr/share/callflow";
 DESTDIR="./out"; #default
 TMPDIR="/tmp";
-removeSL=0; # do not remove callflow.short and callflow.long
+keepSL=0 # do not keep cap.short and cap.long files
+removeDF=0; # do not remove Duplicate Frames
+sessionID=0; # do not use session ID
+order=0; # do not build order file
 
 ##################################
 # Check configuration files :
@@ -68,77 +71,40 @@ do
 		echo "  -o, create an order file with the nodes in FILE.cap"
 		echo "      (Don't forget to redirect output in another file. "
 		echo "      Exemple of use: callflow -o capture.cap > order)"
-		echo "  -t, will use FILE/callflow.short file"
-		echo "  -d, remove duplicate frames in FILE/callflow.long"
-		echo "  -s, add 'Session ID' to Sequence Lines in FILE/callflow.long"
-		echo "  -r, remove files FILE/callflow.short and FILE/callflow.long after proceeding"
+		echo "  -t, use cap.short and cap.long files."
+		echo "      note 1 - if -t and -d are used, only -t is executed."
+		echo "      note 2 - this option sould not be selected on the first run."
+		echo "  -d, remove duplicate frames while computing."
+		echo "      This option should not be selected on the first run."
+		echo "  -s, add a session ID to Sequence Lines in FILE/callflow.long"
 
 		exit 0;
-		;;
-    -t)
-		#inputfile
-		inputfile=$2;
-
-		# Compute DESTDIR
-		DESTDIR=`ls $inputfile | sed -r "s/(.+)\.(.+)/\1/"`;
-		mkdir -p $DESTDIR/frames
-		cp $inputfile $DESTDIR/callflow-source.cap
-
-
 		;;
     -d)
 		#inputfile
 		#we want to remove duplicate frames
-		inputfile=$2;
-
-		# Compute DESTDIR
-		DESTDIR=`ls $inputfile | sed -r "s/(.+)\.(.+)/\1/"`;
-		mkdir -p $DESTDIR/frames
-		cp $inputfile $DESTDIR/callflow-source.cap
-
-
-
-		# Remove duplicate frames
-		awk -f $SETUPDIR/awk-scripts/removedups.awk -v destDir=$DESTDIR < $DESTDIR/callflow.short > $DESTDIR/callflow.short.new
-		rm $DESTDIR/callflow.short
-		mv $DESTDIR/callflow.short.new $DESTDIR/callflow.short
-		exit 0;
+		removeDF=1
+		echo "Duplicate Frames will be removed"
 		;;
+    -t)
+                #keep short and long files
+                keepSL=1
+                echo "Short and Long files will be used"
+                ;;
     -s)
-		if [ sessionFile = none ]; then
+		if [ $sessionFile = none ]; then
 		  echo "You must create either $SETUPDIR/session or ./session to use -s option";
 		  exit 1;
 		fi
-		#inputfile
 		#we want to add "Session ID"
-		inputfile=$2;
-
-		# Compute DESTDIR
-		DESTDIR=`ls $inputfile | sed -r "s/(.+)\.(.+)/\1/"`;
-		mkdir -p $DESTDIR/frames
-		cp $inputfile $DESTDIR/callflow-source.cap
-
-
-
-		awk -f $SETUPDIR/awk-scripts/marksession.awk -v session_token="`cat $sessionFile`" -v destDir=$DESTDIR < $DESTDIR/callflow.short > $DESTDIR/callflow.short.new
-		rm $DESTDIR/callflow.short
-		mv $DESTDIR/callflow.short.new $DESTDIR/callflow.short
-		exit 0;
+		sessionID=1
+		echo "Session ID will be shown"
+		
 		;;
     -o)
 		#inputfile is a cap-file
 		#we want to make an order file
-		inputfile=$2;
-
-		if [ $filterFile != none ]; then
-			echo 'Using the following wireshark display filter:' 1>&2
-			cat $filterFile 1>&2
-			tshark -r $inputfile -R "`cat $filterFile`" -o 'column.format: "Src", "%s", "Port", "%S", "Dest", "%d", "Port", "%D"' | awk '{ printf("%s:%s\n%s:%s\n", $1, $2, $3, $4); }' | sort | uniq
-			else
-			echo 'Warning:  filter file not found -- no filters applied' 1>&2
-			tshark -r $inputfile -o 'column.format: "Src", "%s", "Port", "%S", "Dest", "%d", "Port", "%D"' | awk '{ printf("%s:%s\n%s:%s\n", $1, $2, $3, $4); }' | sort | uniq
-		fi
-		exit 0;
+		order=1
 		;;
     -r)
 		#inputfile is a cap-file
@@ -146,52 +112,109 @@ do
 		inputfile=$2;
 		removeSL=-r;
 
-		# DESTDIR
-		DESTDIR=`ls $inputfile | sed -r "s/(.+)\.(.+)/\1/"`;
-		mkdir -p $DESTDIR/frames
-		cp $inputfile $DESTDIR/callflow-source.cap
-
-		# filterFile
-		if [ $filterFile != none ]; then
-			echo Using the following wireshark display filter:
-			cat $filterFile
-			tshark -r $inputfile -R "`cat $filterFile`" -o 'column.format:"No.","%m","Src","%s","Port","%S","Ignored","%m","Dest","%d","Port","%D","Protocol","%p","Info","%i"' > $DESTDIR/callflow.short
-			tshark -r $inputfile -R "`cat $filterFile`" -V > $DESTDIR/callflow.long
-		else
-			echo 'Warning: filter file not found -- no filters applied'
-			tshark -r $inputfile -o 'column.format: "No.", "%m", "Src", "%s", "Port", "%S", "Ignored", "%m", "Dest", "%d", "Port", "%D", "Protocol", "%p", "Info", "%i"' > $DESTDIR/callflow.short
-			tshark -r $inputfile -V > $DESTDIR/callflow.long
-		fi
-	;;
+		;;
      *)
 		#inputfile is a cap-file
 		#no options
-		inputfile=$1;
+		inputfile=$arg;
 
-		# DESTDIR
-		DESTDIR=`ls $inputfile | sed -r "s/(.+)\.(.+)/\1/"`;
-		mkdir -p $DESTDIR/frames
-		cp $inputfile $DESTDIR/callflow-source.cap
-
-		# filterFile
-		if [ $filterFile != none ]; then
-			echo Using the following wireshark display filter:
-			cat $filterFile
-			tshark -r $inputfile -R "`cat $filterFile`" -o 'column.format:"No.","%m","Src","%s","Port","%S","Ignored","%m","Dest","%d","Port","%D","Protocol","%p","Info","%i"' > $DESTDIR/callflow.short
-			tshark -r $inputfile -R "`cat $filterFile`" -V > $DESTDIR/callflow.long
-		else
-			echo 'Warning: filter file not found -- no filters applied'
-			tshark -r $inputfile -o 'column.format: "No.", "%m", "Src", "%s", "Port", "%S", "Ignored", "%m", "Dest", "%d", "Port", "%D", "Protocol", "%p", "Info", "%i"' > $DESTDIR/callflow.short
-			tshark -r $inputfile -V > $DESTDIR/callflow.long
-		fi
 	;;
   esac
 done
 
 ##################################
+# Check input file
+##################################
+if [ ! -f $inputfile ]; then 
+	echo "Input file does not exists !"
+	exit 1;
+fi
+
+##################################
+# Build short and long files
+##################################
+# DESTDIR
+DESTDIR=`ls $inputfile | sed -r "s/(.+)\.(.+)/\1/"`;
+mkdir -p $DESTDIR
+# Copy cap file into destdir
+cp $inputfile $DESTDIR/callflow-source.cap
+
+# if we do want to build new short and long file
+if [ $keepSL = 0 ]; then
+	# filterFile
+	if [ $filterFile != none ]; then
+		echo Using the following wireshark display filter:
+		cat $filterFile
+		tshark -r $inputfile -R "`cat $filterFile`" -o 'column.format:"No.","%m","Src","%s","Port","%S","Ignored","%m","Dest","%d","Port","%D","Protocol","%p","Info","%i"' > $DESTDIR/callflow.short
+		tshark -r $inputfile -R "`cat $filterFile`" -V > $DESTDIR/callflow.long
+	else
+		echo 'Warning: filter file not found -- no filters applied'
+		tshark -r $inputfile -o 'column.format: "No.", "%m", "Src", "%s", "Port", "%S", "Ignored", "%m", "Dest", "%d", "Port", "%D", "Protocol", "%p", "Info", "%i"' > $DESTDIR/callflow.short
+		tshark -r $inputfile -V > $DESTDIR/callflow.long
+	fi
+else
+	# We want to keep SL files
+	# disable duplicate frame remove
+	removeDF=0
+fi
+
+# We have to check if short and long file exist
+if [ ! -f $DESTDIR/callflow.long ]; then
+	echo "File callflow.long does not exist !"
+	exit 1;
+fi
+if [ ! -f $DESTDIR/callflow.short ]; then
+        echo "File callflow.short does not exist !"
+	exit 1;
+fi
+
+##################################
+# order file
+##################################
+# Build the order file and exit
+if [ $order = 1 ]; then
+	if [ $filterFile != none ]; then
+		echo 'Using the following wireshark display filter:' 1>&2
+		cat $filterFile 1>&2
+		tshark -r $inputfile -R "`cat $filterFile`" -o 'column.format: "Src", "%s", "Port", "%S", "Dest", "%d", "Port", "%D"' | awk '{ printf("%s:%s\n%s:%s\n", $1, $2, $3, $4); }' | sort | uniq
+	else
+		echo 'Warning:  filter file not found -- no filters applied' 1>&2
+		tshark -r $inputfile -o 'column.format: "Src", "%s", "Port", "%S", "Dest", "%d", "Port", "%D"' | awk '{ printf("%s:%s\n%s:%s\n", $1, $2, $3, $4); }' | sort | uniq
+	fi
+	exit 0;
+fi
+
+##################################
+# Remove duplicate Frame
+##################################
+
+if [ $removeDF = 1 ]; then
+	DESTDIR=`ls $inputfile | sed -r "s/(.+)\.(.+)/\1/"`;
+	if [ -d $DESTDIR/frames ]; then
+		echo "Removing Duplicates Frames"
+        else
+                echo "Please run the script without -d once in order to build $DESTDIR directory"
+                exit 1;
+        fi
+	awk -f $SETUPDIR/awk-scripts/removedups.awk -v destDir=$DESTDIR < $DESTDIR/callflow.short > $DESTDIR/callflow.short.new
+	rm $DESTDIR/callflow.short
+	mv $DESTDIR/callflow.short.new $DESTDIR/callflow.short
+fi
+
+##################################
+# Add session ID
+##################################
+if [ $sessionID = 1 ]; then
+	awk -f $SETUPDIR/awk-scripts/marksession.awk -v session_token="`cat $sessionFile`" -v destDir=$DESTDIR < $DESTDIR/callflow.short > $DESTDIR/callflow.short.new
+	rm $DESTDIR/callflow.short
+	mv $DESTDIR/callflow.short.new $DESTDIR/callflow.short
+fi
+
+##################################
 # common
 ##################################
 # Create Frames
+mkdir -p $DESTDIR/frames
 awk -f $SETUPDIR/awk-scripts/long2html.awk -v destDir=$DESTDIR < $DESTDIR/callflow.long
 
 # Compute nodes
@@ -253,12 +276,6 @@ awk -f $TMPDIR/callflow.awk.$PPID \
 
 # Remove temporary files
 \rm $TMPDIR/callflow.*.$PPID
-
-# Remove $DESTDIR/callflow.short and callflow.long if -r option
-if [ $removeSL == "-r" ]; then
-    rm $DESTDIR/callflow.short
-    rm $DESTDIR/callflow.long
-fi
 
 # Check to see if java and the batik rasterizer are installed
 which java 2>&1 > /dev/null
